In [1]:
import pandas as pd

In [2]:
 print(pd.__version__)

1.5.3


In [3]:
A = pd.Series([2,3,4,5],index=['a','b','c','d'])

In [4]:
A.values

array([2, 3, 4, 5], dtype=int64)

In [5]:
type(A.values)

numpy.ndarray

In [6]:
type(A)

pandas.core.series.Series

In [7]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
A['a']

2

In [9]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [10]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grades_dict)

In [11]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [12]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [13]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [14]:
marks['A']

85

In [15]:
marks[0:2]

A    85
B    75
dtype: int64

In [16]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [17]:
grades

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

In [18]:
D = pd.DataFrame({'Marks':marks,'Grades':grades})

In [19]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [20]:
D.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [21]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [22]:
D.values[2,0]

65.0

In [23]:
D.columns

Index(['Marks', 'Grades'], dtype='object')

In [24]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [25]:
D['ScaledMarks'] = 100*(D['Marks']/90)

In [26]:
D

Marks  Grades  ScaledMarks
A     85     4.0    94.444444
B     75     3.5    83.333333
C     65     3.0    72.222222
D     55     2.5    61.111111

In [27]:
del D['ScaledMarks']

In [28]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [29]:
G = D[D['Marks']>70]

In [30]:
G

Marks  Grades
A     85     4.0
B     75     3.5

In [31]:
A = pd.DataFrame([{'a':1,'b':4},{'b':3,'c':9}])

In [32]:
A

a  b    c
0  1.0  4  NaN
1  NaN  3  9.0

In [33]:
A.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0  3  9.0

In [35]:
A = pd.Series(['a','b','c'],index=[1,3,5])

In [36]:
A[1]

'a'

In [37]:
A[1:3] # implicit index

3    b
5    c
dtype: object

In [38]:
A.loc[1:3] # explicit index

1    a
3    b
dtype: object

In [39]:
A.iloc[1:3] # implicit index

3    b
5    c
dtype: object

In [40]:
D

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [41]:
D.iloc[2,:]

Marks     65.0
Grades     3.0
Name: C, dtype: float64

In [42]:
D.iloc[::-1,:]

Marks  Grades
D     55     2.5
C     65     3.0
B     75     3.5
A     85     4.0